// swift-tools-version: 6.0
import PackageDescription

/// A test target for the module's pure logic.
///
/// `apps/mobile/ios` is generated by `expo prebuild`, so a test target added
/// there does not survive. This package compiles the handful of files that have
/// no CoreML, llama.cpp, or Expo dependency and tests them with `swift test`.
/// Everything that needs a real model is verified on a device instead.
let package = Package(
  name: "T3VoiceLogic",
  platforms: [.macOS(.v14)],
  targets: [
    .target(
      name: "T3VoiceLogic",
      path: "ios",
      sources: ["SpeakerFilter.swift", "ReasoningText.swift"]
    ),
    .testTarget(
      name: "T3VoiceLogicTests",
      dependencies: ["T3VoiceLogic"],
      path: "Tests/T3VoiceLogicTests"
    ),
  ]
)
